### ISSUE TITLE
A kind request to add new architectures .

### ISSUE THREAD

**Issue by geekheadxd** [jaskaranSM/drivedlgo#1]
Hey , thanx for this cool work .
Can you please update your package on AUR so that it supports architecture like Archlinuxarm which will help mobile devices to install your package via an emulator like termux . 

Please consider it .

**Comment by jaskaranSM** [comment]
> which will help mobile devices to install your package via an emulator like termux
Afaik it needs to be cross compiled with Android-ndk,  have you tried compiling it with `env GOOS=android GOARCH=arm CC=$NDK_ROOT/bin/arm-linux-androideabi-clang CGO_ENABLED=1 go build`
> update your package on AUR
the version needs updating yes.

**Comment by jaskaranSM** [comment]
Afaik it needs to be cross compiled with Android-ndk, have you tried compiling it with `env GOOS=android GOARCH=arm CC=$NDK_ROOT/bin/arm-linux-androideabi-clang CGO_ENABLED=1 go build`

**Comment by geekheadxd** [comment]
It will be hectic task to cross compile it on my android 10 machine :) 
Can you please do the same by updating your package (if possible) to be compatible with aarch64 architecture . I have ArchLinux | Arm installed on my phone with aarch64 architecture (armv8) . Most android device nowadays come with this architecture . You can easily do this as a developer :)

I use drivedl by user @architdate as it is easy AF to install but have some missing features . Your drivedl-go looks awesome with all of its feature . Please consider it making easy to install on android (in termux ) like the original drivedl does . More user will consider to use it then ! 

🙌 thanks .

**Comment by jaskaranSM** [comment]
Actually compiling on android for android doesnt need cross compilation, compiling on other platform like mac/linux does. I have done an android-arm build of drivedlgo and its working, heres the [link](https://drive.google.com/uc?id=1ehk_lqDKtX3vm7JNkJ8qAxmnEjUGp4hJ&export=download) . I apologize, i don't have an arm64 android device to test, if you need i can do a build with that aswell, About doing a proper release, i use goreleaser workspaces so will have to see how to integrate android-ndk build with it.

**Comment by geekheadxd** [comment]
thanks a lot for considering . I badly need it to work with arm64 . Please have a look in your spare time . 

can you please tell what to do with the zip file . you provided . doesn't have clue how to install with it 😭

**Comment by jaskaranSM** [comment]
Well, extract the zip file in termux. You will get binary of drivedlgo. Then u can run it normally. Push it in a folder which is in path or use ./ infront of it to invoke it. I think arm build should work on arm64 device as for the backwards compaitbilty most of the 64 bit systems have.

**Comment by geekheadxd** [comment]
finally thanks ... 🙌👍
in the first instance : 
CANNOT LINK EXECUTABLE "./drivedlgo/drivedlgo": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit

but after "unset LD_PRELOAD" from google it worked .

**Comment by jaskaranSM** [comment]
> finally thanks ... 🙌👍
> in the first instance :
> CANNOT LINK EXECUTABLE "./drivedlgo/drivedlgo": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
> 
> but after "unset LD_PRELOAD" from google it worked .

Glad to know that your problem has been solved. Will also release Android-Arm(64) builds in future releases.
