### ISSUE TITLE
Can't able to set download directory 

### ISSUE THREAD

**Issue by ronin08** [jaskaranSM/drivedlgo#14]
After providing any download directory with setdldir, it download files in a newly created folder named 'value' in the current directory.

**Comment by jaskaranSM** [comment]
could you please provide more information like the version of drivedlgo, the full command you used?

**Comment by ronin08** [comment]
Version: 1.5
OS: Android 11 (using Termux)
Command: ./drivedlgo setdldir /sdcard/Download/
It even says 'Detected download directory path: /sdcard/Dowmload/' after running the command.

This path is valid as I can navigate to it by 'cd /sdcard/Download/'. Storage permission is already provided.

Even though, it download the file into a new folder named 'value' in the working directory.

**Comment by jaskaranSM** [comment]
![Screenshot_20220701-080847_Termux](https://user-images.githubusercontent.com/37726998/176891853-6080c926-4552-47fe-820f-027012378f0d.jpg)

Looks like it is working fine here. However the sdcard in question i cannot test as my phone does not have a sdcard in it (no sd card slot).

**Comment by jaskaranSM** [comment]
> 

"It even says 'Detected download directory path: /sdcard/Dowmload/' after running the command."  Is that "m" in "Dowmload" a typo?

**Comment by jaskaranSM** [comment]
> Version: 1.5 OS: Android 11 (using Termux) Command: ./drivedlgo setdldir /sdcard/Download/ It even says 'Detected download directory path: /sdcard/Dowmload/' after running the command.
> 
> This path is valid as I can navigate to it by 'cd /sdcard/Download/'. Storage permission is already provided.
> 
> Even though, it download the file into a new folder named 'value' in the working directory.

"It even says 'Detected download directory path: /sdcard/Dowmload/' after running the command." Is that "m" in "Dowmload" a typo?

**Comment by ronin08** [comment]
My phone too doesn't support sdcard. Let me try putting dldir this way.

> ![Screenshot_20220701-080847_Termux](https://user-images.githubusercontent.com/37726998/176891853-6080c926-4552-47fe-820f-027012378f0d.jpg)
> 
> Looks like it is working fine here. However the sdcard in question i cannot test as my phone does not have a sdcard in it (no sd card slot).

My phone too doesn't have an sdcard slot. But it doesn't have that storage folder on the termux home.
I use /sdcard/.. to navigate through phone storage.

**Comment by ronin08** [comment]
> > Version: 1.5 OS: Android 11 (using Termux) Command: ./drivedlgo setdldir /sdcard/Download/ It even says 'Detected download directory path: /sdcard/Dowmload/' after running the command.
> > This path is valid as I can navigate to it by 'cd /sdcard/Download/'. Storage permission is already provided.
> > Even though, it download the file into a new folder named 'value' in the working directory.
> 
> "It even says 'Detected download directory path: /sdcard/Dowmload/' after running the command." Is that "m" in "Dowmload" a typo?

No its a typo in the comment 😅

**Comment by jaskaranSM** [comment]
> My phone too doesn't support sdcard. Let me try putting dldir this way.
> 
> > ![Screenshot_20220701-080847_Termux](https://user-images.githubusercontent.com/37726998/176891853-6080c926-4552-47fe-820f-027012378f0d.jpg)
> > Looks like it is working fine here. However the sdcard in question i cannot test as my phone does not have a sdcard in it (no sd card slot).
> 
> My phone too doesn't have an sdcard slot. But it doesn't have that storage folder on the termux home. I use /sdcard/.. to navigate through phone storage.

Have you done the termux-setup-storage thing?

**Comment by ronin08** [comment]
Ohh Sorry ! Got the glitch.
 Actually to avoid typing ./drivedlgo everytime, I edited the .bash_profile which looks like this:
![IMG_20220701_180318](https://user-images.githubusercontent.com/75478274/176895224-21676eae-982f-427b-bf21-c8cac62ddc8c.jpg)
I forgot to remove that "--path value" 😂. Now I know why it created the value folder, whenever I used dl command.
After your reply, I used ./drivedlgo and it worked.
![IMG_20220701_181113](https://user-images.githubusercontent.com/75478274/176896472-f4001a6c-522d-4ace-a236-90b1da528e00.jpg)


And yes no need to do "termux-setup-storage" things. Just give storage permission to termux from settings or app info. And /sdcard/.. will be your phone storage.
You can delete that storage folder too!

Again, sorry for the hectic discussion.

One question: why haven't you released Android build for version 1.6.1 ? 

😁

**Comment by jaskaranSM** [comment]
> Ohh Sorry ! Got the glitch. Actually to avoid typing ./drivedlgo everytime, I edited the .bash_profile which looks like this: ![IMG_20220701_180318](https://user-images.githubusercontent.com/75478274/176895224-21676eae-982f-427b-bf21-c8cac62ddc8c.jpg) I forgot to remove that "--path value" 😂. Now I know why it created the value folder, whenever I used dl command. After your reply, I used ./drivedlgo and it worked. ![IMG_20220701_181113](https://user-images.githubusercontent.com/75478274/176896472-f4001a6c-522d-4ace-a236-90b1da528e00.jpg)
> 
> And yes no need to do "termux-setup-storage" things. Just give storage permission to termux from settings or app info. And /sdcard/.. will be your phone storage. You can delete that storage folder too!
> 
> Again, sorry for the hectic discussion.
> 
> One question: why haven't you released Android build for version 1.6.1 ?
> 
> 😁

DriveDlGo uses goreleaser for building and pushing the builds. Android builds need cross compiling with Android-NDK. I m not sure if goreleaser supports this form for cross compilation. The previous android builds were done manually on my server. Try compiling it on your phone maybe.

**Comment by ronin08** [comment]
I don't have knowledge about all this, completely noob. If you can manually do this yourself, it's fine. Otherwise no problem. 😊
