### ISSUE TITLE
How to change the default location . 

### ISSUE THREAD

**Issue by geekheadxd** [jaskaranSM/drivedlgo#2]
I am not able to change it .

**Comment by jaskaranSM** [comment]
Default location is the current directory where the command was issued. Use drivedlgo --path "path" <link> to set custom path for this download. Use --help for more info.

**Comment by geekheadxd** [comment]
here is the output : 
$ ./drivedlgo --path "/sdcard"
2021/03/03 06:01:44 Required argument <fileid/link> is missing.
Usage: ./drivedlgo [global options] [arguments...]
For more info: ./drivedlgo --help

**Comment by jaskaranSM** [comment]
> here is the output :
> $ ./drivedlgo --path "/sdcard"
> 2021/03/03 06:01:44 Required argument <fileid/link> is missing.
> Usage: ./drivedlgo [global options] [arguments...]
> For more info: ./drivedlgo --help

Where's the link? You r supposed to use it like drivedlgo --path "/sdcard" "https://drive.google.com..."

**Comment by geekheadxd** [comment]
ohk . it worked . but is there way to make it default so that every time it download in the sdcard without mentioning path

**Comment by jaskaranSM** [comment]
will see if there is a need to add that.
