### ISSUE TITLE
A specific request .

### ISSUE THREAD

**Issue by geekheadxd** [jaskaranSM/drivedlgo#3]
Hey thanks for adding the requested feature to change default download directory ! 
You have given me the binary file of the code to be able to run on Android . Thats of version 1.4 .
Can you please give the binary file of this version 1.5 to run this on Android .

**Comment by jaskaranSM** [comment]
V1.5 Android binaries are there on the releases page. Check again!

**Comment by geekheadxd** [comment]
oops  ! got it . closing this 
thanks
